# Generated by Django 5.0.4 on 2024-07-17 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_article_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 17, 18, 16, 33, 460422, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
